name: Checkout Example

on: workflow_dispatch
jobs:
  checkout-repository:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: show workspace
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          dir
